### ISSUE TITLE
unjustified problem when refering to an operation in an interface

### ISSUE THREAD

**Issue by erelsgl** [GrammaticalFramework/gf-eclipse-plugin#7]
In the following grammar, the token "Agree_Pension_Fund_S" is marked in red, with the following message: "Couldn't resolve reference to Ident 'Agree_Pension_Fund_S'."

incomplete concrete Common_NLP_Eng_2 of Common_NLP_Abs = open Common_NLP_Interface in {
  ... 

  lin Agree_Pension_Fund = Agree_Pension_Fund_S;
 ...  
}

However, this token is defined in the interface:

interface Common_NLP_Interface = {
    oper
        Agree_Pension_Fund_S: {s: Str} -> {s: Str};
}

This also compiles and works well in the GF command line.

**Comment by inariksit** [comment]
What do you have in your .project file? It should be in the same directory with your other files. I got a similar problem, but with RGL operations. I looked at the file, and the problem is that when I had compiled GF from source, I had just downloaded the sources in /tmp. This is (a fragment of) what is stored in the file:

```
    <linkedResources>
            <link>
                    <name>.gfexternal/CatEng.gf</name>
                    <type>1</type>
                    <location>/tmp/GF/lib/src/english/CatEng.gf</location>
            </link>
            <link>
                    <name>.gfexternal/Combinators.gf</name>
                    <type>1</type>
                    <location>/tmp/GF/lib/src/api/Combinators.gf</location>
            </link>
            ...
            ...
```

So, a question: how to change this, other than manually? I have after this downloaded the files again (I realized I'll need them anyway :D) in a different place.

**Comment by johnjcamilleri** [comment]
@erelsgl I will check this out with your example soon.
@inarilistenmaa Are you saying that you moved the files from /tmp ? In this case the plugin should automatically detect and re-write the links. That should be easy to implement, I will get it done soon.

**Comment by johnjcamilleri** [comment]
@erelsgl I am unable to re-create your issue. I used the examples you gave and GFEP does not report any errors. I suspect a problem is being encountered while building your project, and the error you are getting is come kind of side effect. Please try the following:
1. Make sure "Build automatically" is turned on
2. Try cleaning the project from Project &rarr; Clean
3. Check the console and error log to see if you are getting any other build errors.

**Comment by erelsgl** [comment]
Here is what I see in Eclipse log file:

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-19 11:52:28.971
!MESSAGE Couldn't find tags file platform:/resource/.../.gfbuild/mygrammar.gf-tags

**Comment by johnjcamilleri** [comment]
What version of the plugin are you using? (Help &rarr; Install new software &rarr; What's already installed?)
What OS are you using?

**Comment by erelsgl** [comment]
GF Eclipse Plugin   1.3.0.201202081743

Ubuntu 10.04

**Comment by johnjcamilleri** [comment]
Well, firstly I recommend you upgrade to the latest version of the plugin,
1.4.1.x
If the problem persists then the best thing might be if you can send me a
zipped version of your project so I can try to recreate your exact
conditions.

On 19 March 2012 11:21, erelsgl <
reply@reply.github.com

**Comment by erelsgl** [comment]
I installed the new version. Now I get a more detailed message:

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-19 13:48:46.398
!MESSAGE Problem reading tags file: platform:/resource/GeniusBI/etc/templates/JobCandiate/.gfbuild/nlp_incomplete.gf-tags
!STACK 0
org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Resource '/GeniusBI/etc/templates/JobCandiate/.gfbuild/nlp_incomplete.gf-tags' does not exist.
    at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl$WorkbenchHelper.createPlatformResourceInputStream(PlatformResourceURIHandlerImpl.java:222)
    at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl.createInputStream(PlatformResourceURIHandlerImpl.java:452)
    at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:350)
    at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:344)
    at org.grammaticalframework.eclipse.scoping.GFTagBasedGlobalScopeProvider.parseSingleTagsFile(GFTagBasedGlobalScopeProvider.java:201)
    at org.grammaticalframework.eclipse.scoping.GFTagBasedGlobalScopeProvider.parseTagsFile(GFTagBasedGlobalScopeProvider.java:133)
    at org.grammaticalframework.eclipse.scoping.GFTagBasedGlobalScopeProvider.access$0(GFTagBasedGlobalScopeProvider.java:123)
    at org.grammaticalframework.eclipse.scoping.GFTagBasedGlobalScopeProvider$1.get(GFTagBasedGlobalScopeProvider.java:85)
    at org.grammaticalframework.eclipse.scoping.GFTagBasedGlobalScopeProvider$1.get(GFTagBasedGlobalScopeProvider.java:1)
    at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:72)
    at org.grammaticalframework.eclipse.scoping.GFTagBasedGlobalScopeProvider.getScope(GFTagBasedGlobalScopeProvider.java:82)
    at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeProvider.getScope(AbstractGlobalScopeProvider.java:48)
    at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeDelegatingScopeProvider.getGlobalScope(AbstractGlobalScopeDelegatingScopeProvider.java:46)
    at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeDelegatingScopeProvider.getGlobalScope(AbstractGlobalScopeDelegatingScopeProvider.java:42)
    at org.grammaticalframework.eclipse.scoping.GFScopeProvider.getScope(GFScopeProvider.java:76)
    at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
    at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:119)
    at org.grammaticalframework.eclipse.linking.GFLinkingService.getLinkedObjects(GFLinkingService.java:58)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:175)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReference(LazyLinkingResource.java:143)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReferences(LazyLinkingResource.java:104)
    at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:491)
    at org.eclipse.xtext.validation.ResourceValidatorImpl.resolveProxies(ResourceValidatorImpl.java:127)
    at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:62)
    at org.grammaticalframework.eclipse.validation.GFResourceValidator.validate(GFResourceValidator.java:44)
    at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:79)
    at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
    at org.eclipse.xtext.util.concurrent.AbstractReadWriteAcces.readOnly(AbstractReadWriteAcces.java:32)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:78)
    at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:75)
    at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:64)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.eclipse.core.internal.resources.ResourceException: Resource '/GeniusBI/etc/templates/JobCandiate/.gfbuild/nlp_incomplete.gf-tags' does not exist.
    at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:320)
    at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:194)
    at org.eclipse.core.internal.resources.File.getContents(File.java:287)
    at org.eclipse.core.internal.resources.File.getContents(File.java:278)
    at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl$WorkbenchHelper.createPlatformResourceInputStream(PlatformResourceURIHandlerImpl.java:208)
    ... 31 more

**Comment by erelsgl** [comment]
Strangely, when I copied the relevant files from my Java project to a new GF project, the errors disappeared. Now the Eclipse log contains the following: 

!ENTRY org.grammaticalframework.eclipse.ui 1 0 2012-03-19 14:10:08.197
!MESSAGE Incremental build on: gf_eclipse_plugin

!ENTRY org.grammaticalframework.eclipse.ui 1 0 2012-03-19 14:10:08.244
!MESSAGE Built: /gf_eclipse_plugin/interface_test_2/nlp_incomplete.gf

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-19 14:10:08.686
!MESSAGE No EObject found for 1 items.

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-19 14:10:08.686
!MESSAGE No EObject found for 2 items.

... [160 times]

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-19 14:10:08.703
!MESSAGE No EObject found for 160 items.

**Comment by johnjcamilleri** [comment]
Ok, I see the issue now. Automatic building and validation of GF will only work within a GF Project, or more specifically a project which has both the GF Nature and the GF Builder associated with it.

These new log entries look normal.

**Comment by erelsgl** [comment]
OK, and how do I associate the GF Nature and GF Builder with an existing project?

**Comment by johnjcamilleri** [comment]
The nature can be added or removed by right-clicking on the project and choosing **Add/Remove GF Nature**. You should see a small GF icon overlayed on your project icon if the nature is correctly added.

For the builder there is no such shortcut, so the best way is to open your `.project` file manually and add the following `<buildCommand>`:

```
<buildSpec>
  ...
  <buildCommand>
    <name>org.grammaticalframework.eclipse.ui.build.GFBuilderID</name>
    <arguments>
    </arguments>
  </buildCommand>
  ...
</buildSpec>
```

I will add a shortcut for this in a future release of the plugin.

In the meanwhile, these things are all documented on the [GFEP homepage](http://www.grammaticalframework.org/eclipse/).

**Comment by erelsgl** [comment]
Great! That completely solved the problem.

Thank you very much!
